### ISSUE TITLE
【勘误】加密货币的描述有误

### ISSUE THREAD

**Issue by G3G4X5X6** [Web3-Club/Blockchain-Developer-roadmap_Chinese#2]
![image](https://user-images.githubusercontent.com/87740076/217976962-3b19b37a-fcdc-48ad-b3be-9132043973cf.png)

**Comment by yanboishere** [comment]
请问下具体是哪里？

**Comment by yanboishere** [comment]
好的，我看一下。

**Comment by yanboishere** [comment]
感谢你的指出，新版已修改。 👍
